/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentShell_LocalCPlusPlusAgentLoader */

#ifndef _Included_agentShell_LocalCPlusPlusAgentLoader
#define _Included_agentShell_LocalCPlusPlusAgentLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agentShell_LocalCPlusPlusAgentLoader
 * Method:    JNImakeAgentList
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_agentShell_LocalCPlusPlusAgentLoader_JNImakeAgentList
  (JNIEnv *, jobject, jstring);

/*
 * Class:     agentShell_LocalCPlusPlusAgentLoader
 * Method:    JNIgetAgentName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_agentShell_LocalCPlusPlusAgentLoader_JNIgetAgentName
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentShell_LocalCPlusPlusAgentLoader
 * Method:    JNIgetAgentParams
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_agentShell_LocalCPlusPlusAgentLoader_JNIgetAgentParams
  (JNIEnv *, jobject, jint);

/*
 * Class:     agentShell_LocalCPlusPlusAgentLoader
 * Method:    JNIgetAgentCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_agentShell_LocalCPlusPlusAgentLoader_JNIgetAgentCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
