/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class agentShell_JNIAgent */

#ifndef _Included_agentShell_JNIAgent
#define _Included_agentShell_JNIAgent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIloadAgent
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_agentShell_JNIAgent_JNIloadAgent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIagentinit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_agentShell_JNIAgent_JNIagentinit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIagentstart
 * Signature: (II[I[D)V
 */
JNIEXPORT void JNICALL Java_agentShell_JNIAgent_JNIagentstart
  (JNIEnv *, jobject, jint, jint, jintArray, jdoubleArray);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIagentstep
 * Signature: (DII[I[D)V
 */
JNIEXPORT void JNICALL Java_agentShell_JNIAgent_JNIagentstep
  (JNIEnv *, jobject, jdouble, jint, jint, jintArray, jdoubleArray);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIagentend
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_agentShell_JNIAgent_JNIagentend
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIagentcleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentShell_JNIAgent_JNIagentcleanup
  (JNIEnv *, jobject);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIagentfreeze
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_agentShell_JNIAgent_JNIagentfreeze
  (JNIEnv *, jobject);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIagentmessage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_agentShell_JNIAgent_JNIagentmessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIgetvalueforstate
 * Signature: (II[I[D)D
 */
JNIEXPORT jdouble JNICALL Java_agentShell_JNIAgent_JNIgetvalueforstate
  (JNIEnv *, jobject, jint, jint, jintArray, jdoubleArray);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIgetInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_agentShell_JNIAgent_JNIgetInt
  (JNIEnv *, jobject);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIgetIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_agentShell_JNIAgent_JNIgetIntArray
  (JNIEnv *, jobject);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIgetDouble
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_agentShell_JNIAgent_JNIgetDouble
  (JNIEnv *, jobject);

/*
 * Class:     agentShell_JNIAgent
 * Method:    JNIgetDoubleArray
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_agentShell_JNIAgent_JNIgetDoubleArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
