/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class environmentShell_LocalCPlusPlusEnvironmentLoader */

#ifndef _Included_environmentShell_LocalCPlusPlusEnvironmentLoader
#define _Included_environmentShell_LocalCPlusPlusEnvironmentLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     environmentShell_LocalCPlusPlusEnvironmentLoader
 * Method:    JNIgetEnvParams
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_environmentShell_LocalCPlusPlusEnvironmentLoader_JNIgetEnvParams
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
