/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class environmentShell_DylibGrabber */

#ifndef _Included_environmentShell_DylibGrabber
#define _Included_environmentShell_DylibGrabber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     environmentShell_DylibGrabber
 * Method:    jniIsThisAValidEnv
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_environmentShell_DylibGrabber_jniIsThisAValidEnv
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
