#	READ:
#
#	If you experience errors please refer to the individual
#	makefiles within the projects for an explanation of how
#	to fix them

EnvLoaders:
	cd CPPEnvLoader && make
	cd CPPAgentLoader && make

clean:
	cd CPPEnvLoader && make clean
	cd CPPAgentLoader && make clean